apiVersion: v1
kind: Service
metadata:
  name: web-search 

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: web-search

  ports:
    - name: http
      port: 80
      nodePort: 30090

  type: NodePort

---
kind: Service
apiVersion: v1
metadata:
  name: database 
spec:
  selector:
    app: database 
  ports:
  - port: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: db-connect

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: db-connect

  ports:
    - name: http
      port: 80
      nodePort: 30091

  type: NodePort



